---
title: "Eval-grades"
author: "Antoine Calvayrac"
format: html
---

library
```{r}
#| message: false
library(here)
here::i_am("eval-grades.Rproj")
library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
```
Question 1:

```{r}
grades <- read_csv("grades.csv")
```

Question 2:

```{r}
total_grades <- grades |> summarise(total=n()) |> pull(total)
paste("The dataset contains", total_grades, "grades")
```

Question 3:

```{r}
num_students <- grades |> distinct(id) |> summarise(n = n()) |> pull(n)
paste("The dataset contains", num_students , "students")
```

Question 4:

```{r}
#| message: false
students <- grades |> select(id, group) |> distinct(id, group) 
```

```{r}
students |> slice_tail(n = 5) |> knitr::kable()
```


Question 5:

```{r}
ggplot(students, aes(x = group)) + 
  geom_bar()+
  labs(title = "Number of Students per Group", 
       x = "Group", 
       y = "Number of Students")
```

Question 6:

```{r}
average_Rune_Glyph <- grades |> filter(course == "Runecrafting and Glyphwork") |> group_by(group) |> summarise(average = mean(grade))
```

```{r}
ggplot(average_Rune_Glyph, aes(x = group, y =average)) + 
  geom_col()+
  labs(title = "Average per Group", 
       x = "Group", 
       y = "Grade")
```

Question 7:





Question 8:


```{r}
grades |> group_by(id, group) |> summarise(n = n()) |> head(10)
```

```{r}
grades_stat <- grades |> group_by(id, group) |> summarise(min_grade = min(grade), max_grade = max(grade), mean_grade = mean(grade), median_grade = median(grade) )
```

```{r}
library(knitr)
print(kable(grades_stat, format = "markdown", caption = "Summary Statistics of Grades per Student"))
```

Question 9:

```{r}
#|mmessage: false
nb_grades_necromancy <- grades |> filter(course == "Necromancy and Spirit Summoning") |> group_by(id, group) |> summarise(n =n()) 
```

```{r}
nb_grades_necromancy |> head(10)
```

Question 10:

```{r}
nb_grades_necromancy |> group_by(n) |> summarise(num_students =n())
```

```{r}
#|message: false
grades_distribution <- nb_grades_necromancy |> group_by(n) |> summarise(num_students =n())
```

```{r}
ggplot(grades_distribution, aes(x=n, y= num_students))+ 
  geom_col()+
  labs(title = "Distribution of Number of Grades in Necromancy and Spirit Summoning",
       x = "Number of Grades",
       y = "Number of Students")
```

Question 11:

```{r}
ggplot(nb_grades_necromancy, aes(x = n))+
  geom_bar()+ 
    facet_wrap(vars(group))
```

Question 12: 

```{r}
#|message: false
average_grade <- grades |> select(-trimester) |> group_by(id, group, course) |> summarise(average_grades = mean(grade))

wider_df <- average_grade |> pivot_wider(names_from = "course", values_from = "average_grades" )
```

```{r}
wider_df |> head(10)
```

Question 13:

```{r}
ggplot(wider_df, aes(x = `Runecrafting and Glyphwork`, y = `Elemental Mastery and Control`))+
  geom_point(alpha = 0.25) + 
  labs(
    title = "Average Grades in Elemental Mastery and Control vs. Average Grades in Runecrafting and Glyphwork",
    x = "Average Grades in Runecrafting and Glyphwork",
    y = "Average Grades in Elemental Mastery and Control")+
  geom_smooth(method = "lm", color = "red", linetype = "dashed") 
  
```

Question 14:

```{r}
wider_df |> group_by(group) |> summarise(correlation = cor(`Illusion and Enchantment`, `Elemental Mastery and Control`))
```

Question 15:

```{r}
wider_df |> group_by(group) |> summarise(correlation = cor(`Illusion and Enchantment`, `Elemental Mastery and Control`)) |> filter(correlation >0.3)
```

